// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
)

// AccessLogApplyConfiguration represents a declarative configuration of the AccessLog type for use
// with apply.
type AccessLogApplyConfiguration struct {
	Filter *apiv1alpha1.CELExpression         `json:"filter,omitempty"`
	Fields *AccessLogFieldsApplyConfiguration `json:"fields,omitempty"`
}

// AccessLogApplyConfiguration constructs a declarative configuration of the AccessLog type for use with
// apply.
func AccessLog() *AccessLogApplyConfiguration {
	return &AccessLogApplyConfiguration{}
}

// WithFilter sets the Filter field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Filter field is set to the value of the last call.
func (b *AccessLogApplyConfiguration) WithFilter(value apiv1alpha1.CELExpression) *AccessLogApplyConfiguration {
	b.Filter = &value
	return b
}

// WithFields sets the Fields field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Fields field is set to the value of the last call.
func (b *AccessLogApplyConfiguration) WithFields(value *AccessLogFieldsApplyConfiguration) *AccessLogApplyConfiguration {
	b.Fields = value
	return b
}
