// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
)

// AccessLogFieldsApplyConfiguration represents a declarative configuration of the AccessLogFields type for use
// with apply.
type AccessLogFieldsApplyConfiguration struct {
	Remove []string                             `json:"remove,omitempty"`
	Add    map[string]apiv1alpha1.CELExpression `json:"add,omitempty"`
}

// AccessLogFieldsApplyConfiguration constructs a declarative configuration of the AccessLogFields type for use with
// apply.
func AccessLogFields() *AccessLogFieldsApplyConfiguration {
	return &AccessLogFieldsApplyConfiguration{}
}

// WithRemove adds the given value to the Remove field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Remove field.
func (b *AccessLogFieldsApplyConfiguration) WithRemove(values ...string) *AccessLogFieldsApplyConfiguration {
	for i := range values {
		b.Remove = append(b.Remove, values[i])
	}
	return b
}

// WithAdd puts the entries into the Add field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Add field,
// overwriting an existing map entries in Add field with the same key.
func (b *AccessLogFieldsApplyConfiguration) WithAdd(entries map[string]apiv1alpha1.CELExpression) *AccessLogFieldsApplyConfiguration {
	if b.Add == nil && len(entries) > 0 {
		b.Add = make(map[string]apiv1alpha1.CELExpression, len(entries))
	}
	for k, v := range entries {
		b.Add[k] = v
	}
	return b
}
