// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// AnthropicConfigApplyConfiguration represents a declarative configuration of the AnthropicConfig type for use
// with apply.
type AnthropicConfigApplyConfiguration struct {
	Version *string `json:"apiVersion,omitempty"`
}

// AnthropicConfigApplyConfiguration constructs a declarative configuration of the AnthropicConfig type for use with
// apply.
func AnthropicConfig() *AnthropicConfigApplyConfiguration {
	return &AnthropicConfigApplyConfiguration{}
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *AnthropicConfigApplyConfiguration) WithVersion(value string) *AnthropicConfigApplyConfiguration {
	b.Version = &value
	return b
}
