// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
)

// AuthorizationApplyConfiguration represents a declarative configuration of the Authorization type for use
// with apply.
type AuthorizationApplyConfiguration struct {
	Policy *AuthorizationPolicyApplyConfiguration `json:"policy,omitempty"`
	Action *apiv1alpha1.AuthorizationPolicyAction `json:"action,omitempty"`
}

// AuthorizationApplyConfiguration constructs a declarative configuration of the Authorization type for use with
// apply.
func Authorization() *AuthorizationApplyConfiguration {
	return &AuthorizationApplyConfiguration{}
}

// WithPolicy sets the Policy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Policy field is set to the value of the last call.
func (b *AuthorizationApplyConfiguration) WithPolicy(value *AuthorizationPolicyApplyConfiguration) *AuthorizationApplyConfiguration {
	b.Policy = value
	return b
}

// WithAction sets the Action field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Action field is set to the value of the last call.
func (b *AuthorizationApplyConfiguration) WithAction(value apiv1alpha1.AuthorizationPolicyAction) *AuthorizationApplyConfiguration {
	b.Action = &value
	return b
}
