// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
)

// AuthorizationPolicyApplyConfiguration represents a declarative configuration of the AuthorizationPolicy type for use
// with apply.
type AuthorizationPolicyApplyConfiguration struct {
	MatchExpressions []apiv1alpha1.CELExpression `json:"matchExpressions,omitempty"`
}

// AuthorizationPolicyApplyConfiguration constructs a declarative configuration of the AuthorizationPolicy type for use with
// apply.
func AuthorizationPolicy() *AuthorizationPolicyApplyConfiguration {
	return &AuthorizationPolicyApplyConfiguration{}
}

// WithMatchExpressions adds the given value to the MatchExpressions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the MatchExpressions field.
func (b *AuthorizationPolicyApplyConfiguration) WithMatchExpressions(values ...apiv1alpha1.CELExpression) *AuthorizationPolicyApplyConfiguration {
	for i := range values {
		b.MatchExpressions = append(b.MatchExpressions, values[i])
	}
	return b
}
