// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// BackendPolicySpecApplyConfiguration represents a declarative configuration of the BackendPolicySpec type for use
// with apply.
type BackendPolicySpecApplyConfiguration struct {
	TargetRefs      []LocalPolicyTargetReferenceApplyConfiguration `json:"targetRefs,omitempty"`
	TargetSelectors []LocalPolicyTargetSelectorApplyConfiguration  `json:"targetSelectors,omitempty"`
	TCP             *BackendTCPApplyConfiguration                  `json:"tcp,omitempty"`
	HTTP            *BackendHTTPApplyConfiguration                 `json:"http,omitempty"`
	MCP             *BackendMCPApplyConfiguration                  `json:"mcp,omitempty"`
	AI              *BackendAIApplyConfiguration                   `json:"ai,omitempty"`
	Auth            *BackendAuthApplyConfiguration                 `json:"auth,omitempty"`
	TLS             *TLSApplyConfiguration                         `json:"tls,omitempty"`
}

// BackendPolicySpecApplyConfiguration constructs a declarative configuration of the BackendPolicySpec type for use with
// apply.
func BackendPolicySpec() *BackendPolicySpecApplyConfiguration {
	return &BackendPolicySpecApplyConfiguration{}
}

// WithTargetRefs adds the given value to the TargetRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TargetRefs field.
func (b *BackendPolicySpecApplyConfiguration) WithTargetRefs(values ...*LocalPolicyTargetReferenceApplyConfiguration) *BackendPolicySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTargetRefs")
		}
		b.TargetRefs = append(b.TargetRefs, *values[i])
	}
	return b
}

// WithTargetSelectors adds the given value to the TargetSelectors field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TargetSelectors field.
func (b *BackendPolicySpecApplyConfiguration) WithTargetSelectors(values ...*LocalPolicyTargetSelectorApplyConfiguration) *BackendPolicySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTargetSelectors")
		}
		b.TargetSelectors = append(b.TargetSelectors, *values[i])
	}
	return b
}

// WithTCP sets the TCP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TCP field is set to the value of the last call.
func (b *BackendPolicySpecApplyConfiguration) WithTCP(value *BackendTCPApplyConfiguration) *BackendPolicySpecApplyConfiguration {
	b.TCP = value
	return b
}

// WithHTTP sets the HTTP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HTTP field is set to the value of the last call.
func (b *BackendPolicySpecApplyConfiguration) WithHTTP(value *BackendHTTPApplyConfiguration) *BackendPolicySpecApplyConfiguration {
	b.HTTP = value
	return b
}

// WithMCP sets the MCP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MCP field is set to the value of the last call.
func (b *BackendPolicySpecApplyConfiguration) WithMCP(value *BackendMCPApplyConfiguration) *BackendPolicySpecApplyConfiguration {
	b.MCP = value
	return b
}

// WithAI sets the AI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AI field is set to the value of the last call.
func (b *BackendPolicySpecApplyConfiguration) WithAI(value *BackendAIApplyConfiguration) *BackendPolicySpecApplyConfiguration {
	b.AI = value
	return b
}

// WithAuth sets the Auth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Auth field is set to the value of the last call.
func (b *BackendPolicySpecApplyConfiguration) WithAuth(value *BackendAuthApplyConfiguration) *BackendPolicySpecApplyConfiguration {
	b.Auth = value
	return b
}

// WithTLS sets the TLS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLS field is set to the value of the last call.
func (b *BackendPolicySpecApplyConfiguration) WithTLS(value *TLSApplyConfiguration) *BackendPolicySpecApplyConfiguration {
	b.TLS = value
	return b
}
