// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// BackendHTTPApplyConfiguration represents a declarative configuration of the BackendHTTP type for use
// with apply.
type BackendHTTPApplyConfiguration struct {
	IdleTimeout                 *v1.Duration       `json:"idleTimeout,omitempty"`
	InitialStreamWindowSize     *resource.Quantity `json:"initialStreamWindowSize,omitempty"`
	InitialConnectionWindowSize *resource.Quantity `json:"initialConnectionWindowSize,omitempty"`
	MaxConcurrentStreams        *int32             `json:"maxConcurrentStreams,omitempty"`
}

// BackendHTTPApplyConfiguration constructs a declarative configuration of the BackendHTTP type for use with
// apply.
func BackendHTTP() *BackendHTTPApplyConfiguration {
	return &BackendHTTPApplyConfiguration{}
}

// WithIdleTimeout sets the IdleTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IdleTimeout field is set to the value of the last call.
func (b *BackendHTTPApplyConfiguration) WithIdleTimeout(value v1.Duration) *BackendHTTPApplyConfiguration {
	b.IdleTimeout = &value
	return b
}

// WithInitialStreamWindowSize sets the InitialStreamWindowSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InitialStreamWindowSize field is set to the value of the last call.
func (b *BackendHTTPApplyConfiguration) WithInitialStreamWindowSize(value resource.Quantity) *BackendHTTPApplyConfiguration {
	b.InitialStreamWindowSize = &value
	return b
}

// WithInitialConnectionWindowSize sets the InitialConnectionWindowSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InitialConnectionWindowSize field is set to the value of the last call.
func (b *BackendHTTPApplyConfiguration) WithInitialConnectionWindowSize(value resource.Quantity) *BackendHTTPApplyConfiguration {
	b.InitialConnectionWindowSize = &value
	return b
}

// WithMaxConcurrentStreams sets the MaxConcurrentStreams field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxConcurrentStreams field is set to the value of the last call.
func (b *BackendHTTPApplyConfiguration) WithMaxConcurrentStreams(value int32) *BackendHTTPApplyConfiguration {
	b.MaxConcurrentStreams = &value
	return b
}
