// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// BackendAuthApplyConfiguration represents a declarative configuration of the BackendAuth type for use
// with apply.
type BackendAuthApplyConfiguration struct {
	Inline    *string                  `json:"inline,omitempty"`
	SecretRef *v1.LocalObjectReference `json:"secretRef,omitempty"`
}

// BackendAuthApplyConfiguration constructs a declarative configuration of the BackendAuth type for use with
// apply.
func BackendAuth() *BackendAuthApplyConfiguration {
	return &BackendAuthApplyConfiguration{}
}

// WithInline sets the Inline field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Inline field is set to the value of the last call.
func (b *BackendAuthApplyConfiguration) WithInline(value string) *BackendAuthApplyConfiguration {
	b.Inline = &value
	return b
}

// WithSecretRef sets the SecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretRef field is set to the value of the last call.
func (b *BackendAuthApplyConfiguration) WithSecretRef(value v1.LocalObjectReference) *BackendAuthApplyConfiguration {
	b.SecretRef = &value
	return b
}
