// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
)

// BackendMCPApplyConfiguration represents a declarative configuration of the BackendMCP type for use
// with apply.
type BackendMCPApplyConfiguration struct {
	Authorization  *AuthorizationApplyConfiguration `json:"authorization,omitempty"`
	Authentication *apiv1alpha1.MCPAuthentication   `json:"authentication,omitempty"`
}

// BackendMCPApplyConfiguration constructs a declarative configuration of the BackendMCP type for use with
// apply.
func BackendMCP() *BackendMCPApplyConfiguration {
	return &BackendMCPApplyConfiguration{}
}

// WithAuthorization sets the Authorization field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Authorization field is set to the value of the last call.
func (b *BackendMCPApplyConfiguration) WithAuthorization(value *AuthorizationApplyConfiguration) *BackendMCPApplyConfiguration {
	b.Authorization = value
	return b
}

// WithAuthentication sets the Authentication field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Authentication field is set to the value of the last call.
func (b *BackendMCPApplyConfiguration) WithAuthentication(value apiv1alpha1.MCPAuthentication) *BackendMCPApplyConfiguration {
	b.Authentication = &value
	return b
}
