// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// BackendAIApplyConfiguration represents a declarative configuration of the BackendAI type for use
// with apply.
type BackendAIApplyConfiguration struct {
	PromptEnrichment *AIPromptEnrichmentApplyConfiguration `json:"prompt,omitempty"`
	PromptGuard      *AIPromptGuardApplyConfiguration      `json:"promptGuard,omitempty"`
	Defaults         []FieldDefaultApplyConfiguration      `json:"defaults,omitempty"`
	Overrides        []FieldDefaultApplyConfiguration      `json:"overrides,omitempty"`
	ModelAliases     map[string]string                     `json:"modelAliases,omitempty"`
}

// BackendAIApplyConfiguration constructs a declarative configuration of the BackendAI type for use with
// apply.
func BackendAI() *BackendAIApplyConfiguration {
	return &BackendAIApplyConfiguration{}
}

// WithPromptEnrichment sets the PromptEnrichment field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PromptEnrichment field is set to the value of the last call.
func (b *BackendAIApplyConfiguration) WithPromptEnrichment(value *AIPromptEnrichmentApplyConfiguration) *BackendAIApplyConfiguration {
	b.PromptEnrichment = value
	return b
}

// WithPromptGuard sets the PromptGuard field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PromptGuard field is set to the value of the last call.
func (b *BackendAIApplyConfiguration) WithPromptGuard(value *AIPromptGuardApplyConfiguration) *BackendAIApplyConfiguration {
	b.PromptGuard = value
	return b
}

// WithDefaults adds the given value to the Defaults field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Defaults field.
func (b *BackendAIApplyConfiguration) WithDefaults(values ...*FieldDefaultApplyConfiguration) *BackendAIApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithDefaults")
		}
		b.Defaults = append(b.Defaults, *values[i])
	}
	return b
}

// WithOverrides adds the given value to the Overrides field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Overrides field.
func (b *BackendAIApplyConfiguration) WithOverrides(values ...*FieldDefaultApplyConfiguration) *BackendAIApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOverrides")
		}
		b.Overrides = append(b.Overrides, *values[i])
	}
	return b
}

// WithModelAliases puts the entries into the ModelAliases field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ModelAliases field,
// overwriting an existing map entries in ModelAliases field with the same key.
func (b *BackendAIApplyConfiguration) WithModelAliases(entries map[string]string) *BackendAIApplyConfiguration {
	if b.ModelAliases == nil && len(entries) > 0 {
		b.ModelAliases = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ModelAliases[k] = v
	}
	return b
}
