// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// BedrockConfigApplyConfiguration represents a declarative configuration of the BedrockConfig type for use
// with apply.
type BedrockConfigApplyConfiguration struct {
	Region *string `json:"region,omitempty"`
}

// BedrockConfigApplyConfiguration constructs a declarative configuration of the BedrockConfig type for use with
// apply.
func BedrockConfig() *BedrockConfigApplyConfiguration {
	return &BedrockConfigApplyConfiguration{}
}

// WithRegion sets the Region field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Region field is set to the value of the last call.
func (b *BedrockConfigApplyConfiguration) WithRegion(value string) *BedrockConfigApplyConfiguration {
	b.Region = &value
	return b
}
