// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
)

// BodyTransformationApplyConfiguration represents a declarative configuration of the BodyTransformation type for use
// with apply.
type BodyTransformationApplyConfiguration struct {
	Value *apiv1alpha1.CELExpression `json:"value,omitempty"`
}

// BodyTransformationApplyConfiguration constructs a declarative configuration of the BodyTransformation type for use with
// apply.
func BodyTransformation() *BodyTransformationApplyConfiguration {
	return &BodyTransformationApplyConfiguration{}
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *BodyTransformationApplyConfiguration) WithValue(value apiv1alpha1.CELExpression) *BodyTransformationApplyConfiguration {
	b.Value = &value
	return b
}
