// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CSRFPolicyApplyConfiguration represents a declarative configuration of the CSRFPolicy type for use
// with apply.
type CSRFPolicyApplyConfiguration struct {
	AdditionalOrigins []string `json:"additionalOrigins,omitempty"`
}

// CSRFPolicyApplyConfiguration constructs a declarative configuration of the CSRFPolicy type for use with
// apply.
func CSRFPolicy() *CSRFPolicyApplyConfiguration {
	return &CSRFPolicyApplyConfiguration{}
}

// WithAdditionalOrigins adds the given value to the AdditionalOrigins field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AdditionalOrigins field.
func (b *CSRFPolicyApplyConfiguration) WithAdditionalOrigins(values ...string) *CSRFPolicyApplyConfiguration {
	for i := range values {
		b.AdditionalOrigins = append(b.AdditionalOrigins, values[i])
	}
	return b
}
