// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// DirectResponseApplyConfiguration represents a declarative configuration of the DirectResponse type for use
// with apply.
type DirectResponseApplyConfiguration struct {
	StatusCode *int32  `json:"status,omitempty"`
	Body       *string `json:"body,omitempty"`
}

// DirectResponseApplyConfiguration constructs a declarative configuration of the DirectResponse type for use with
// apply.
func DirectResponse() *DirectResponseApplyConfiguration {
	return &DirectResponseApplyConfiguration{}
}

// WithStatusCode sets the StatusCode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StatusCode field is set to the value of the last call.
func (b *DirectResponseApplyConfiguration) WithStatusCode(value int32) *DirectResponseApplyConfiguration {
	b.StatusCode = &value
	return b
}

// WithBody sets the Body field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Body field is set to the value of the last call.
func (b *DirectResponseApplyConfiguration) WithBody(value string) *DirectResponseApplyConfiguration {
	b.Body = &value
	return b
}
