// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// FrontendTCPApplyConfiguration represents a declarative configuration of the FrontendTCP type for use
// with apply.
type FrontendTCPApplyConfiguration struct {
	KeepAlive *TCPKeepaliveApplyConfiguration `json:"keepAlive,omitempty"`
}

// FrontendTCPApplyConfiguration constructs a declarative configuration of the FrontendTCP type for use with
// apply.
func FrontendTCP() *FrontendTCPApplyConfiguration {
	return &FrontendTCPApplyConfiguration{}
}

// WithKeepAlive sets the KeepAlive field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KeepAlive field is set to the value of the last call.
func (b *FrontendTCPApplyConfiguration) WithKeepAlive(value *TCPKeepaliveApplyConfiguration) *FrontendTCPApplyConfiguration {
	b.KeepAlive = value
	return b
}
