// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// FrontendPolicySpecApplyConfiguration represents a declarative configuration of the FrontendPolicySpec type for use
// with apply.
type FrontendPolicySpecApplyConfiguration struct {
	TargetRefs      []LocalPolicyTargetReferenceApplyConfiguration `json:"targetRefs,omitempty"`
	TargetSelectors []LocalPolicyTargetSelectorApplyConfiguration  `json:"targetSelectors,omitempty"`
	HTTP            *FrontendHTTPApplyConfiguration                `json:"http,omitempty"`
	TLS             *FrontendTLSApplyConfiguration                 `json:"tls,omitempty"`
	TCP             *FrontendTCPApplyConfiguration                 `json:"tcp,omitempty"`
}

// FrontendPolicySpecApplyConfiguration constructs a declarative configuration of the FrontendPolicySpec type for use with
// apply.
func FrontendPolicySpec() *FrontendPolicySpecApplyConfiguration {
	return &FrontendPolicySpecApplyConfiguration{}
}

// WithTargetRefs adds the given value to the TargetRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TargetRefs field.
func (b *FrontendPolicySpecApplyConfiguration) WithTargetRefs(values ...*LocalPolicyTargetReferenceApplyConfiguration) *FrontendPolicySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTargetRefs")
		}
		b.TargetRefs = append(b.TargetRefs, *values[i])
	}
	return b
}

// WithTargetSelectors adds the given value to the TargetSelectors field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TargetSelectors field.
func (b *FrontendPolicySpecApplyConfiguration) WithTargetSelectors(values ...*LocalPolicyTargetSelectorApplyConfiguration) *FrontendPolicySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTargetSelectors")
		}
		b.TargetSelectors = append(b.TargetSelectors, *values[i])
	}
	return b
}

// WithHTTP sets the HTTP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HTTP field is set to the value of the last call.
func (b *FrontendPolicySpecApplyConfiguration) WithHTTP(value *FrontendHTTPApplyConfiguration) *FrontendPolicySpecApplyConfiguration {
	b.HTTP = value
	return b
}

// WithTLS sets the TLS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLS field is set to the value of the last call.
func (b *FrontendPolicySpecApplyConfiguration) WithTLS(value *FrontendTLSApplyConfiguration) *FrontendPolicySpecApplyConfiguration {
	b.TLS = value
	return b
}

// WithTCP sets the TCP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TCP field is set to the value of the last call.
func (b *FrontendPolicySpecApplyConfiguration) WithTCP(value *FrontendTCPApplyConfiguration) *FrontendPolicySpecApplyConfiguration {
	b.TCP = value
	return b
}
