// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"
)

// FrontendHTTPApplyConfiguration represents a declarative configuration of the FrontendHTTP type for use
// with apply.
type FrontendHTTPApplyConfiguration struct {
	MaxBufferSize             *int           `json:"maxBufferSize,omitempty"`
	HTTP1MaxHeaders           *int           `json:"http1MaxHeaders,omitempty"`
	HTTP1IdleTimeout          *time.Duration `json:"http1IdleTimeout,omitempty"`
	HTTP2WindowSize           *uint32        `json:"http2WindowSize,omitempty"`
	HTTP2ConnectionWindowSize *uint32        `json:"http2ConnectionWindowSize,omitempty"`
	HTTP2FrameSize            *uint32        `json:"http2FrameSize,omitempty"`
	HTTP2KeepaliveInterval    *time.Duration `json:"http2KeepaliveInterval,omitempty"`
	HTTP2KeepaliveTimeout     *time.Duration `json:"http2KeepaliveTimeout,omitempty"`
}

// FrontendHTTPApplyConfiguration constructs a declarative configuration of the FrontendHTTP type for use with
// apply.
func FrontendHTTP() *FrontendHTTPApplyConfiguration {
	return &FrontendHTTPApplyConfiguration{}
}

// WithMaxBufferSize sets the MaxBufferSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxBufferSize field is set to the value of the last call.
func (b *FrontendHTTPApplyConfiguration) WithMaxBufferSize(value int) *FrontendHTTPApplyConfiguration {
	b.MaxBufferSize = &value
	return b
}

// WithHTTP1MaxHeaders sets the HTTP1MaxHeaders field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HTTP1MaxHeaders field is set to the value of the last call.
func (b *FrontendHTTPApplyConfiguration) WithHTTP1MaxHeaders(value int) *FrontendHTTPApplyConfiguration {
	b.HTTP1MaxHeaders = &value
	return b
}

// WithHTTP1IdleTimeout sets the HTTP1IdleTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HTTP1IdleTimeout field is set to the value of the last call.
func (b *FrontendHTTPApplyConfiguration) WithHTTP1IdleTimeout(value time.Duration) *FrontendHTTPApplyConfiguration {
	b.HTTP1IdleTimeout = &value
	return b
}

// WithHTTP2WindowSize sets the HTTP2WindowSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HTTP2WindowSize field is set to the value of the last call.
func (b *FrontendHTTPApplyConfiguration) WithHTTP2WindowSize(value uint32) *FrontendHTTPApplyConfiguration {
	b.HTTP2WindowSize = &value
	return b
}

// WithHTTP2ConnectionWindowSize sets the HTTP2ConnectionWindowSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HTTP2ConnectionWindowSize field is set to the value of the last call.
func (b *FrontendHTTPApplyConfiguration) WithHTTP2ConnectionWindowSize(value uint32) *FrontendHTTPApplyConfiguration {
	b.HTTP2ConnectionWindowSize = &value
	return b
}

// WithHTTP2FrameSize sets the HTTP2FrameSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HTTP2FrameSize field is set to the value of the last call.
func (b *FrontendHTTPApplyConfiguration) WithHTTP2FrameSize(value uint32) *FrontendHTTPApplyConfiguration {
	b.HTTP2FrameSize = &value
	return b
}

// WithHTTP2KeepaliveInterval sets the HTTP2KeepaliveInterval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HTTP2KeepaliveInterval field is set to the value of the last call.
func (b *FrontendHTTPApplyConfiguration) WithHTTP2KeepaliveInterval(value time.Duration) *FrontendHTTPApplyConfiguration {
	b.HTTP2KeepaliveInterval = &value
	return b
}

// WithHTTP2KeepaliveTimeout sets the HTTP2KeepaliveTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HTTP2KeepaliveTimeout field is set to the value of the last call.
func (b *FrontendHTTPApplyConfiguration) WithHTTP2KeepaliveTimeout(value time.Duration) *FrontendHTTPApplyConfiguration {
	b.HTTP2KeepaliveTimeout = &value
	return b
}
