// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"
)

// FrontendTLSApplyConfiguration represents a declarative configuration of the FrontendTLS type for use
// with apply.
type FrontendTLSApplyConfiguration struct {
	HandshakeTimeout *time.Duration `json:"handshakeTimeout,omitempty"`
}

// FrontendTLSApplyConfiguration constructs a declarative configuration of the FrontendTLS type for use with
// apply.
func FrontendTLS() *FrontendTLSApplyConfiguration {
	return &FrontendTLSApplyConfiguration{}
}

// WithHandshakeTimeout sets the HandshakeTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HandshakeTimeout field is set to the value of the last call.
func (b *FrontendTLSApplyConfiguration) WithHandshakeTimeout(value time.Duration) *FrontendTLSApplyConfiguration {
	b.HandshakeTimeout = &value
	return b
}
