// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// GeminiConfigApplyConfiguration represents a declarative configuration of the GeminiConfig type for use
// with apply.
type GeminiConfigApplyConfiguration struct {
	ApiVersion *string `json:"apiVersion,omitempty"`
}

// GeminiConfigApplyConfiguration constructs a declarative configuration of the GeminiConfig type for use with
// apply.
func GeminiConfig() *GeminiConfigApplyConfiguration {
	return &GeminiConfigApplyConfiguration{}
}

// WithApiVersion sets the ApiVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ApiVersion field is set to the value of the last call.
func (b *GeminiConfigApplyConfiguration) WithApiVersion(value string) *GeminiConfigApplyConfiguration {
	b.ApiVersion = &value
	return b
}
