// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
)

// RateLimitDescriptorEntryApplyConfiguration represents a declarative configuration of the RateLimitDescriptorEntry type for use
// with apply.
type RateLimitDescriptorEntryApplyConfiguration struct {
	Key   *string                    `json:"key,omitempty"`
	Value *apiv1alpha1.CELExpression `json:"value,omitempty"`
}

// RateLimitDescriptorEntryApplyConfiguration constructs a declarative configuration of the RateLimitDescriptorEntry type for use with
// apply.
func RateLimitDescriptorEntry() *RateLimitDescriptorEntryApplyConfiguration {
	return &RateLimitDescriptorEntryApplyConfiguration{}
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *RateLimitDescriptorEntryApplyConfiguration) WithKey(value string) *RateLimitDescriptorEntryApplyConfiguration {
	b.Key = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *RateLimitDescriptorEntryApplyConfiguration) WithValue(value apiv1alpha1.CELExpression) *RateLimitDescriptorEntryApplyConfiguration {
	b.Value = &value
	return b
}
