// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "sigs.k8s.io/gateway-api/apis/v1"
)

// RetryApplyConfiguration represents a declarative configuration of the Retry type for use
// with apply.
type RetryApplyConfiguration struct {
	v1.HTTPCORSFilter `json:",inline"`
}

// RetryApplyConfiguration constructs a declarative configuration of the Retry type for use with
// apply.
func Retry() *RetryApplyConfiguration {
	return &RetryApplyConfiguration{}
}
