// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
)

// TracingApplyConfiguration represents a declarative configuration of the Tracing type for use
// with apply.
type TracingApplyConfiguration struct {
	Provider       *TracingProviderApplyConfiguration  `json:"provider,omitempty"`
	ClientSampling *apiv1alpha1.CELExpression          `json:"clientSampling,omitempty"`
	RandomSampling *apiv1alpha1.CELExpression          `json:"randomSampling,omitempty"`
	Fields         []AccessLogFieldsApplyConfiguration `json:"fields,omitempty"`
}

// TracingApplyConfiguration constructs a declarative configuration of the Tracing type for use with
// apply.
func Tracing() *TracingApplyConfiguration {
	return &TracingApplyConfiguration{}
}

// WithProvider sets the Provider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Provider field is set to the value of the last call.
func (b *TracingApplyConfiguration) WithProvider(value *TracingProviderApplyConfiguration) *TracingApplyConfiguration {
	b.Provider = value
	return b
}

// WithClientSampling sets the ClientSampling field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientSampling field is set to the value of the last call.
func (b *TracingApplyConfiguration) WithClientSampling(value apiv1alpha1.CELExpression) *TracingApplyConfiguration {
	b.ClientSampling = &value
	return b
}

// WithRandomSampling sets the RandomSampling field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RandomSampling field is set to the value of the last call.
func (b *TracingApplyConfiguration) WithRandomSampling(value apiv1alpha1.CELExpression) *TracingApplyConfiguration {
	b.RandomSampling = &value
	return b
}

// WithFields adds the given value to the Fields field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Fields field.
func (b *TracingApplyConfiguration) WithFields(values ...*AccessLogFieldsApplyConfiguration) *TracingApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithFields")
		}
		b.Fields = append(b.Fields, *values[i])
	}
	return b
}
