// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// TrafficPolicySpecApplyConfiguration represents a declarative configuration of the TrafficPolicySpec type for use
// with apply.
type TrafficPolicySpecApplyConfiguration struct {
	Phase           *string                                                       `json:"phase,omitempty"`
	TargetRefs      []LocalPolicyTargetReferenceWithSectionNameApplyConfiguration `json:"targetRefs,omitempty"`
	TargetSelectors []LocalPolicyTargetSelectorWithSectionNameApplyConfiguration  `json:"targetSelectors,omitempty"`
	Transformation  *TransformationPolicyApplyConfiguration                       `json:"transformation,omitempty"`
	ExtProc         *ExtProcPolicyApplyConfiguration                              `json:"extProc,omitempty"`
	ExtAuth         *ExtAuthPolicyApplyConfiguration                              `json:"extAuth,omitempty"`
	RateLimit       *RateLimitApplyConfiguration                                  `json:"rateLimit,omitempty"`
	Cors            *CorsPolicyApplyConfiguration                                 `json:"cors,omitempty"`
	Csrf            *CSRFPolicyApplyConfiguration                                 `json:"csrf,omitempty"`
	HeaderModifiers *HeaderModifiersApplyConfiguration                            `json:"headerModifiers,omitempty"`
	AutoHostRewrite *bool                                                         `json:"autoHostRewrite,omitempty"`
	Timeouts        *TimeoutsApplyConfiguration                                   `json:"timeouts,omitempty"`
	Retry           *RetryApplyConfiguration                                      `json:"retry,omitempty"`
	DirectResponse  *DirectResponseApplyConfiguration                             `json:"directResponse,omitempty"`
	Authorization   *AuthorizationApplyConfiguration                              `json:"authorization,omitempty"`
	AccessLog       []AccessLogApplyConfiguration                                 `json:"accessLog,omitempty"`
	Tracing         *TracingApplyConfiguration                                    `json:"tracing,omitempty"`
}

// TrafficPolicySpecApplyConfiguration constructs a declarative configuration of the TrafficPolicySpec type for use with
// apply.
func TrafficPolicySpec() *TrafficPolicySpecApplyConfiguration {
	return &TrafficPolicySpecApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *TrafficPolicySpecApplyConfiguration) WithPhase(value string) *TrafficPolicySpecApplyConfiguration {
	b.Phase = &value
	return b
}

// WithTargetRefs adds the given value to the TargetRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TargetRefs field.
func (b *TrafficPolicySpecApplyConfiguration) WithTargetRefs(values ...*LocalPolicyTargetReferenceWithSectionNameApplyConfiguration) *TrafficPolicySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTargetRefs")
		}
		b.TargetRefs = append(b.TargetRefs, *values[i])
	}
	return b
}

// WithTargetSelectors adds the given value to the TargetSelectors field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TargetSelectors field.
func (b *TrafficPolicySpecApplyConfiguration) WithTargetSelectors(values ...*LocalPolicyTargetSelectorWithSectionNameApplyConfiguration) *TrafficPolicySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTargetSelectors")
		}
		b.TargetSelectors = append(b.TargetSelectors, *values[i])
	}
	return b
}

// WithTransformation sets the Transformation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Transformation field is set to the value of the last call.
func (b *TrafficPolicySpecApplyConfiguration) WithTransformation(value *TransformationPolicyApplyConfiguration) *TrafficPolicySpecApplyConfiguration {
	b.Transformation = value
	return b
}

// WithExtProc sets the ExtProc field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExtProc field is set to the value of the last call.
func (b *TrafficPolicySpecApplyConfiguration) WithExtProc(value *ExtProcPolicyApplyConfiguration) *TrafficPolicySpecApplyConfiguration {
	b.ExtProc = value
	return b
}

// WithExtAuth sets the ExtAuth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExtAuth field is set to the value of the last call.
func (b *TrafficPolicySpecApplyConfiguration) WithExtAuth(value *ExtAuthPolicyApplyConfiguration) *TrafficPolicySpecApplyConfiguration {
	b.ExtAuth = value
	return b
}

// WithRateLimit sets the RateLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RateLimit field is set to the value of the last call.
func (b *TrafficPolicySpecApplyConfiguration) WithRateLimit(value *RateLimitApplyConfiguration) *TrafficPolicySpecApplyConfiguration {
	b.RateLimit = value
	return b
}

// WithCors sets the Cors field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cors field is set to the value of the last call.
func (b *TrafficPolicySpecApplyConfiguration) WithCors(value *CorsPolicyApplyConfiguration) *TrafficPolicySpecApplyConfiguration {
	b.Cors = value
	return b
}

// WithCsrf sets the Csrf field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Csrf field is set to the value of the last call.
func (b *TrafficPolicySpecApplyConfiguration) WithCsrf(value *CSRFPolicyApplyConfiguration) *TrafficPolicySpecApplyConfiguration {
	b.Csrf = value
	return b
}

// WithHeaderModifiers sets the HeaderModifiers field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HeaderModifiers field is set to the value of the last call.
func (b *TrafficPolicySpecApplyConfiguration) WithHeaderModifiers(value *HeaderModifiersApplyConfiguration) *TrafficPolicySpecApplyConfiguration {
	b.HeaderModifiers = value
	return b
}

// WithAutoHostRewrite sets the AutoHostRewrite field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AutoHostRewrite field is set to the value of the last call.
func (b *TrafficPolicySpecApplyConfiguration) WithAutoHostRewrite(value bool) *TrafficPolicySpecApplyConfiguration {
	b.AutoHostRewrite = &value
	return b
}

// WithTimeouts sets the Timeouts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Timeouts field is set to the value of the last call.
func (b *TrafficPolicySpecApplyConfiguration) WithTimeouts(value *TimeoutsApplyConfiguration) *TrafficPolicySpecApplyConfiguration {
	b.Timeouts = value
	return b
}

// WithRetry sets the Retry field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Retry field is set to the value of the last call.
func (b *TrafficPolicySpecApplyConfiguration) WithRetry(value *RetryApplyConfiguration) *TrafficPolicySpecApplyConfiguration {
	b.Retry = value
	return b
}

// WithDirectResponse sets the DirectResponse field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DirectResponse field is set to the value of the last call.
func (b *TrafficPolicySpecApplyConfiguration) WithDirectResponse(value *DirectResponseApplyConfiguration) *TrafficPolicySpecApplyConfiguration {
	b.DirectResponse = value
	return b
}

// WithAuthorization sets the Authorization field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Authorization field is set to the value of the last call.
func (b *TrafficPolicySpecApplyConfiguration) WithAuthorization(value *AuthorizationApplyConfiguration) *TrafficPolicySpecApplyConfiguration {
	b.Authorization = value
	return b
}

// WithAccessLog adds the given value to the AccessLog field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AccessLog field.
func (b *TrafficPolicySpecApplyConfiguration) WithAccessLog(values ...*AccessLogApplyConfiguration) *TrafficPolicySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAccessLog")
		}
		b.AccessLog = append(b.AccessLog, *values[i])
	}
	return b
}

// WithTracing sets the Tracing field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Tracing field is set to the value of the last call.
func (b *TrafficPolicySpecApplyConfiguration) WithTracing(value *TracingApplyConfiguration) *TrafficPolicySpecApplyConfiguration {
	b.Tracing = value
	return b
}
