// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/applyconfiguration/api/v1alpha1"
	v1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
	typedapiv1alpha1 "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/typed/api/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeFrontendPolicies implements FrontendPolicyInterface
type fakeFrontendPolicies struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.FrontendPolicy, *v1alpha1.FrontendPolicyList, *apiv1alpha1.FrontendPolicyApplyConfiguration]
	Fake *FakeGatewayV1alpha1
}

func newFakeFrontendPolicies(fake *FakeGatewayV1alpha1, namespace string) typedapiv1alpha1.FrontendPolicyInterface {
	return &fakeFrontendPolicies{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.FrontendPolicy, *v1alpha1.FrontendPolicyList, *apiv1alpha1.FrontendPolicyApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("frontendpolicies"),
			v1alpha1.SchemeGroupVersion.WithKind("FrontendPolicy"),
			func() *v1alpha1.FrontendPolicy { return &v1alpha1.FrontendPolicy{} },
			func() *v1alpha1.FrontendPolicyList { return &v1alpha1.FrontendPolicyList{} },
			func(dst, src *v1alpha1.FrontendPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.FrontendPolicyList) []*v1alpha1.FrontendPolicy {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.FrontendPolicyList, items []*v1alpha1.FrontendPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
