// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/typed/api/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeAgentgatewayParameterses implements AgentgatewayParametersInterface
type fakeAgentgatewayParameterses struct {
	*gentype.FakeClientWithList[*v1alpha1.AgentgatewayParameters, *v1alpha1.AgentgatewayParametersList]
	Fake *FakeGatewayV1alpha1
}

func newFakeAgentgatewayParameterses(fake *FakeGatewayV1alpha1, namespace string) apiv1alpha1.AgentgatewayParametersInterface {
	return &fakeAgentgatewayParameterses{
		gentype.NewFakeClientWithList[*v1alpha1.AgentgatewayParameters, *v1alpha1.AgentgatewayParametersList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("agentgatewayparameterses"),
			v1alpha1.SchemeGroupVersion.WithKind("AgentgatewayParameters"),
			func() *v1alpha1.AgentgatewayParameters { return &v1alpha1.AgentgatewayParameters{} },
			func() *v1alpha1.AgentgatewayParametersList { return &v1alpha1.AgentgatewayParametersList{} },
			func(dst, src *v1alpha1.AgentgatewayParametersList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.AgentgatewayParametersList) []*v1alpha1.AgentgatewayParameters {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.AgentgatewayParametersList, items []*v1alpha1.AgentgatewayParameters) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
