// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
	scheme "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// AgentgatewayParametersesGetter has a method to return a AgentgatewayParametersInterface.
// A group's client should implement this interface.
type AgentgatewayParametersesGetter interface {
	AgentgatewayParameterses(namespace string) AgentgatewayParametersInterface
}

// AgentgatewayParametersInterface has methods to work with AgentgatewayParameters resources.
type AgentgatewayParametersInterface interface {
	Create(ctx context.Context, agentgatewayParameters *apiv1alpha1.AgentgatewayParameters, opts v1.CreateOptions) (*apiv1alpha1.AgentgatewayParameters, error)
	Update(ctx context.Context, agentgatewayParameters *apiv1alpha1.AgentgatewayParameters, opts v1.UpdateOptions) (*apiv1alpha1.AgentgatewayParameters, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, agentgatewayParameters *apiv1alpha1.AgentgatewayParameters, opts v1.UpdateOptions) (*apiv1alpha1.AgentgatewayParameters, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.AgentgatewayParameters, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.AgentgatewayParametersList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.AgentgatewayParameters, err error)
	AgentgatewayParametersExpansion
}

// agentgatewayParameterses implements AgentgatewayParametersInterface
type agentgatewayParameterses struct {
	*gentype.ClientWithList[*apiv1alpha1.AgentgatewayParameters, *apiv1alpha1.AgentgatewayParametersList]
}

// newAgentgatewayParameterses returns a AgentgatewayParameterses
func newAgentgatewayParameterses(c *GatewayV1alpha1Client, namespace string) *agentgatewayParameterses {
	return &agentgatewayParameterses{
		gentype.NewClientWithList[*apiv1alpha1.AgentgatewayParameters, *apiv1alpha1.AgentgatewayParametersList](
			"agentgatewayparameterses",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.AgentgatewayParameters { return &apiv1alpha1.AgentgatewayParameters{} },
			func() *apiv1alpha1.AgentgatewayParametersList { return &apiv1alpha1.AgentgatewayParametersList{} },
		),
	}
}
