// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	applyconfigurationapiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/applyconfiguration/api/v1alpha1"
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
	scheme "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// FrontendPoliciesGetter has a method to return a FrontendPolicyInterface.
// A group's client should implement this interface.
type FrontendPoliciesGetter interface {
	FrontendPolicies(namespace string) FrontendPolicyInterface
}

// FrontendPolicyInterface has methods to work with FrontendPolicy resources.
type FrontendPolicyInterface interface {
	Create(ctx context.Context, frontendPolicy *apiv1alpha1.FrontendPolicy, opts v1.CreateOptions) (*apiv1alpha1.FrontendPolicy, error)
	Update(ctx context.Context, frontendPolicy *apiv1alpha1.FrontendPolicy, opts v1.UpdateOptions) (*apiv1alpha1.FrontendPolicy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, frontendPolicy *apiv1alpha1.FrontendPolicy, opts v1.UpdateOptions) (*apiv1alpha1.FrontendPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.FrontendPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.FrontendPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.FrontendPolicy, err error)
	Apply(ctx context.Context, frontendPolicy *applyconfigurationapiv1alpha1.FrontendPolicyApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.FrontendPolicy, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, frontendPolicy *applyconfigurationapiv1alpha1.FrontendPolicyApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.FrontendPolicy, err error)
	FrontendPolicyExpansion
}

// frontendPolicies implements FrontendPolicyInterface
type frontendPolicies struct {
	*gentype.ClientWithListAndApply[*apiv1alpha1.FrontendPolicy, *apiv1alpha1.FrontendPolicyList, *applyconfigurationapiv1alpha1.FrontendPolicyApplyConfiguration]
}

// newFrontendPolicies returns a FrontendPolicies
func newFrontendPolicies(c *GatewayV1alpha1Client, namespace string) *frontendPolicies {
	return &frontendPolicies{
		gentype.NewClientWithListAndApply[*apiv1alpha1.FrontendPolicy, *apiv1alpha1.FrontendPolicyList, *applyconfigurationapiv1alpha1.FrontendPolicyApplyConfiguration](
			"frontendpolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.FrontendPolicy { return &apiv1alpha1.FrontendPolicy{} },
			func() *apiv1alpha1.FrontendPolicyList { return &apiv1alpha1.FrontendPolicyList{} },
		),
	}
}
